spring:
  profiles:
    active: dev
---
server:
  port: 8002
spring:
  application:
    name: USER-PRODUCT-AIGOU  #服务的名字
  profiles: dev
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aigou
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka  #服务注册的注册中心的地址
mybatis-plus:
  mapper-locations: classpath:cn/itsource/*Mapper.xml
  type-aliases-package: cn.itsource.domain,cn.itsource.query

---
server:
  port: 8003
spring:
  application:
    name: USER-PRODUCT-AIGOU-TEST  #服务的名字
  profiles: test
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aigou_test
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka  #服务注册的注册中心的地址
mybatis-plus:
  mapper-locations: classpath:cn/itsource/*Mapper.xml
  type-aliases-package: cn.itsource.domain,cn.itsource.query
